HairSalon/Models/Client.cs
namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string PreferredStyle { get; set; }
    public string Treatments { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Models/StylistClientContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

HairSalon/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name", "Phone", "Address");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

HairSalon/Controllers/StylistController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Client/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new client</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  @Html.LabelFor(model => model.PreferredStyle)
  @Html.TextBoxFor(model => model.PreferredStyle)

  @Html.LabelFor(model => model.Treatments)
  @Html.TextBoxFor(model => model.Treatments)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Client/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this client?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Client/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Phone): @Html.DisplayFor(model => model.Phone)<h3></h3>
<h3>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)<h3>
<h3>@Html.DisplayNameFor(model => model.PreferredStyle): @Html.DisplayFor(model => model.PreferredStyle)<h3></h3>
<h3>@Html.DisplayNameFor(model => model.Treatments): @Html.DisplayFor(model => model.Treatments)<h3></h3>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Client/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit Clients</h2>

<h4>Edit this client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  @Html.LabelFor(model => model.PreferredStyle)
  @Html.EditorFor(model => model.PreferredStyle)

  @Html.LabelFor(model => model.Treatments)
  @Html.EditorFor(model => model.Treatments)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to client list", "Index")</p>

HairSalon/Views/Client/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No Clients have been added yet!</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p>@Html.ActionLink("Add new Client", "Create")</p>

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<div class="jumbotron">
<h4>Add a new client</h4>
</div>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  @Html.LabelFor(model => model.PreferredStyle)
  @Html.TextBoxFor(model => model.PreferredStyle)

  @Html.LabelFor(model => model.Treatments)
  @Html.TextBoxFor(model => model.Treatments)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Add new client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<div class="jumbotron">
<h2>Are you sure you want to delete this client?</h2>
</div>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<div class="jumbotron">
<h2>Client Details</h2>
</div>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Phone): @Html.DisplayFor(model => model.Phone)<h3></h3>
<h3>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)<h3>
<h3>@Html.DisplayNameFor(model => model.PreferredStyle): @Html.DisplayFor(model => model.PreferredStyle)<h3></h3>
<h3>@Html.DisplayNameFor(model => model.Treatments): @Html.DisplayFor(model => model.Treatments)<h3></h3>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<div class="jumbotron">
<h2>Edit Clients</h2>
</div>

<h4>Edit this client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ClientId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  @Html.LabelFor(model => model.PreferredStyle)
  @Html.EditorFor(model => model.PreferredStyle)

  @Html.LabelFor(model => model.Treatments)
  @Html.EditorFor(model => model.Treatments)

  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to client list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<div class="jumbotron">
<h1>Clients</h1>
</div>

@if (@Model.Count == 0)
{
  <h3>No Clients have been added yet!</h3>
} 

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p>@Html.ActionLink("Add new Client", "Create")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="jumbotron">
<h1>Welcome to Mullets R Us Salon!</h1>
<img src="https://media.glamour.com/photos/5695e39e93ef4b09520f3f43/master/w_1600%2Cc_limit/beauty-blogs-girls-in-the-beauty-department-0707-mullet-illegal-zoo-discount_bd.jpg" alt="Mullet Photo" />
</div>
<p>@Html.ActionLink("See all clients", "Index", "Clients")</p> 
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mullets R Us!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body class="page">
    <div class="container">
      <br>
      <br>
      <br>
      <br>
    @RenderBody()
  </body>
</html>

HairSalon/Views/Stylist/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  
  
  <input type="submit" value="Add new Stylist" />
}
<p>@Html.ActionLink("Show all Stylists", "Index")</p>

HairSalon/Views/Stylist/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Stylist Profile</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylist/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this Stylists Profile: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylist/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No Stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
<div class="jumbotron">
  <h1>Add a new Stylist here!</h1>
</div>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)

  
  
  <input type="submit" value="Add new Stylist" />
}
<p>@Html.ActionLink("Show all Stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this stylist?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<div class="jumbotron">
  <h1>Stylist Details</h1>
</div>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
<div class="jumbotron">
<h2>Edit</h2>
</div>

<h4>Edit this Stylists Profile: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<div class="jumbotron">
  <h1>Stylists at Mullets R Us Salon:</h1>
</div>

@if (@Model.Count == 0)
{
  <h3>No Stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>